language: go

go:
  - "1.11.5"
  - tip

install: 
- go get
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls 

script:
- go get github.com/ConnorJarvis/P2P-Communication
- go test -v -covermode=count -coverprofile=coverage.out
- $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $repo_token